const SEARCH_COMPUTERS = 'computer/SEARCH_COMPUTERS';
const UPDATE_COMPUTERS_PING = 'computer/UPDATE_COMPUTERS_PING';
const UPDATE_TABLE = 'computer/UPDATE_TABLE';

export { SEARCH_COMPUTERS, UPDATE_COMPUTERS_PING, UPDATE_TABLE };
