const SEARCH_COMPUTERS = 'computer/SEARCH_COMPUTERS';
const UPDATE_COMPUTERS_PING = 'computer/UPDATE_COMPUTERS_PING';
const UPDATE_COMPUTERS_AFTER_DELETE = 'computer/UPDATE_COMPUTERS_AFTER_DELETE';
export { SEARCH_COMPUTERS, UPDATE_COMPUTERS_PING, UPDATE_COMPUTERS_AFTER_DELETE };
